language: node_js
node_js:
 - 12.16.1
cache: yarn

install: 
 - yarn install


script:
 - yarn test:unit
 - yarn run build

before_deploy: 
 - tar -czvf ./dist/battleship.tar.gz ./dist/js
deploy: 
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 local_dir: dist

 on:
  branch: master